### ISSUE TITLE
ThemeBuilder produces different zero-width space character in the compiled CSS (issue in dart-sass)

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#91] opened 2024-04-24 07:48 UTC
**Describe the bug**
The CSS compiled from ThemeBuilder (using the dart-sass compiler) generates ZWSP (zero-width space character), which is problematic in some corner cases where the end applications won't be able to interpret the invisible symbol properly.

**To Reproduce**
1. Open ThemeBuilder and export the default theme.
2.  Obserive the value for some selectors like .k-window-title::before and compare it to the same value coming from the NPM installation of the theme (or from the CDN link).

**Expected behavior**
To have the same UTF8 representation of the ZWSP.

**Screenshots**
![Screenshot 2024-04-24 at 9 53 25](https://github.com/telerik/themebuilder/assets/18008302/6a30e405-77c0-450a-85ab-f9e0c31f74ad)

**Components technology and version**
If applicable and related to the Kendo/Telerik components - write the technology and component version.

**Additional context**
Add any other context about the problem here.TB Q1 2024

reported through t.1649213

- [ ] Issue 1 - Reproducible in Fluent

**Comment by Martin-Hristov** [comment] 2024-05-08 08:00
Issue 1 - Reproducible in Fluent

**Comment by imtodor** [comment] 2024-05-08 08:16
> Issue 1 - Reproducible in Fluent

This is caused because of the distribution file in the Kendo Theme Fluent package. Reported to Kendo team.

**Comment by rkirilov** [comment] 2024-05-16 10:44
Fixed in Q2 2024

**Closed as completed by rkirilov** 2024-05-16 10:44 UTC
Labels: Bug
